#################### data path Directories ####################
raw_data_dir : '/media/josephdistefano/DataBase/joseph_data/AHEAD-data/raw'
proccessed_data_dir : '/media/josephdistefano/DataBase/joseph_data/AHEAD-data/processed'
interim_data_dir : '/media/josephdistefano/DataBase/joseph_data/AHEAD-data/interm'

#################### Model Path Directories ####################
model_save_dir_seas : '/media/josephdistefano/DataBase/joseph_data/AHEAD-data/models/SEAS/'
model_save_dir_agil: '/media/josephdistefano/DataBase/joseph_data/AHEAD-data/models/AGIL/'
model_save_dir_bc: '/media/josephdistefano/DataBase/joseph_data/AHEAD-data/models/BC/'
model_save_dir_gaze: '/media/josephdistefano/DataBase/joseph_data/AHEAD-data/models/GAZE/'

#### These valid actions are based off of atari gym version 0.26.0 and translated to ####
#### the actions listed in the actions_enums.txt file that comes with the atarihead dataset ####
valid_actions : {
'breakout' : [0, 1, 3, 4],
'asterix' : [0, 2, 3, 4, 5, 6, 7, 8, 9],
'centipede' : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
'ms_pacman' : [0, 2, 3, 4, 5, 6, 7, 8, 9],
'phoenix' : [0, 1, 3, 4, 5, 11, 12, 13],
'seaquest' : [0 ,1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
'venture' : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
'space_invaders' : [0, 1, 3, 4, 11, 12],
'freeway' : [0 ,1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
'alien' : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
'riverraid' : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
'road_runner' : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
'name_this_game' : [0, 1, 3, 4, 11, 12],
'demon_attack' : [0, 2, 3, 4, 5, 6, 7, 8, 9],
'enduro' : [0, 2, 3, 4, 5, 6, 7, 8, 9],
'frostbite' : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
'hero' : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 0, 11, 12, 13, 14, 15, 16, 17],
'montezuma_revenge' : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
'bank_heist' : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
'berzerk' : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
}

##
runs_dir : 'runs/'
VIS_PREDS_DIR : 'data/vis/'
tar_bz2_extension : '.tar.bz2'
HDF_CMP_TYPE : 'gzip'
HDF_CMP_LEVEL : null
STACK_SIZE : 4
BATCH_SIZE : 32
DATA_TYPES : ['frames', 'actions', 'gazes']